/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
module.exports = {
  docsSidebar: [
    {
      type: "doc",
      id: "quickstart",
      label: "Overview",
    },
    {
      type: "doc",
      id: "ARCHITECTURE",
      label: "Architecture",
    },
    {
      type: "category",
      label: "Design Docs",
      items: [
        {
          type: "autogenerated",
          dirName: "design-docs",
        },
      ],
    },
    {
      type: "category",
      label: "Execution Plans",
      items: [
        {
          type: "autogenerated",
          dirName: "exec-plans",
        },
      ],
    },
    {
      type: "category",
      label: "Product Specs",
      items: [
        {
          type: "autogenerated",
          dirName: "product-specs",
        },
      ],
    },
    {
      type: "category",
      label: "References",
      items: [
        {
          type: "autogenerated",
          dirName: "references",
        },
      ],
    },
    {
      type: "category",
      label: "Releases",
      items: [
        {
          type: "autogenerated",
          dirName: "releases",
        },
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        {
          type: "autogenerated",
          dirName: "features",
        },
      ],
    },
    {
      type: "category",
      label: "Specialists",
      items: [
        {
          type: "autogenerated",
          dirName: "specialists",
        },
      ],
    },
  ],
};
