/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
module.exports = {
  docsSidebar: [
    {
      type: "doc",
      id: "quickstart",
      label: "Quickstart",
    },
    {
      type: "doc",
      id: "ARCHITECTURE",
      label: "Architecture",
    },
    {
      type: "category",
      label: "Product Specs",
      items: [
        {
          type: "autogenerated",
          dirName: "product-specs",
        },
      ],
    },
    {
      type: "category",
      label: "Releases",
      items: [
        {
          type: "autogenerated",
          dirName: "releases",
        },
      ],
    },
    {
      type: "category",
      label: "Features",
      items: [
        {
          type: "autogenerated",
          dirName: "features",
        },
      ],
    },
  ],
};
