/**
 * Constrained TSX compiler + sandboxed module loader for Canvas artifacts.
 *
 * Compiles agent-generated TSX source into a React component using sucrase,
 * then evaluates it inside a restricted module scope where the only available
 * import is `cursor/canvas` (plus the legacy `@canvas-sdk` alias).
 *
 * Security boundaries:
 *  - Only the Canvas SDK aliases are resolvable; any other import throws.
 *  - No access to `window`, `document`, `fetch`, `localStorage`, etc.
 *  - No dynamic `import()` — only synchronous `require()` via the shim.
 *  - Sucrase strips TypeScript types but does NOT execute code.
 */

import { transform } from "sucrase";
import React from "react";

import * as CanvasSDK from "@/client/canvas-sdk";
import { getCanvasGenerationContract } from "@/core/canvas/generation-contract";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface CompileResult {
  ok: true;
  Component: React.ComponentType;
}

export interface CompileError {
  ok: false;
  error: string;
}

export type CompileOutcome = CompileResult | CompileError;

// ---------------------------------------------------------------------------
// Allowed module whitelist
// ---------------------------------------------------------------------------

/**
 * Map of module specifiers that compiled canvas code is allowed to require.
 * Any specifier not present here will cause a runtime error.
 */
const MODULE_WHITELIST: Record<string, unknown> = {
  react: React,
  "cursor/canvas": CanvasSDK,
  "@canvas-sdk": CanvasSDK,
};

function normalizeCanvasModuleSpecifier(specifier: string): string {
  if (specifier.startsWith("cursor/canvas/")) {
    return "cursor/canvas";
  }
  if (specifier.startsWith("@canvas-sdk/")) {
    return "@canvas-sdk";
  }

  const sdkPrefixes = getCanvasGenerationContract().imports.normalizedPrefixes;

  for (const prefix of sdkPrefixes) {
    if (specifier === prefix) {
      return "cursor/canvas";
    }
    if (specifier.startsWith(`${prefix}/`)) {
      return "cursor/canvas";
    }
  }

  return specifier;
}

// ---------------------------------------------------------------------------
// Compiler
// ---------------------------------------------------------------------------

/**
 * Compile agent-generated TSX source into a mountable React component.
 *
 * The source must `export default` a function component (no props required).
 * It may import from `react` and the Canvas SDK alias only.
 *
 * Example source:
 * ```tsx
 * import { Stack, H1, Text, BarChart } from "cursor/canvas";
 *
 * export default function MyCanvas() {
 *   return (
 *     <Stack gap={16}>
 *       <H1>Hello Canvas</H1>
 *       <Text tone="secondary">Generated by an agent</Text>
 *     </Stack>
 *   );
 * }
 * ```
 */
export function compileCanvasTsx(source: string): CompileOutcome {
  // Step 1: Transpile TSX → JS (CJS-style with require/exports)
  let jsCode: string;
  try {
    const result = transform(source, {
      transforms: ["typescript", "jsx", "imports"],
      jsxRuntime: "classic",
      production: true,
    });
    jsCode = result.code;
  } catch (err) {
    return {
      ok: false,
      error: `TSX compilation failed: ${err instanceof Error ? err.message : String(err)}`,
    };
  }

  // Step 2: Execute in a constrained scope
  try {
    const moduleExports: Record<string, unknown> = {};
    const fakeModule = { exports: moduleExports };

    const constrainedRequire = (specifier: string): unknown => {
      const normalizedSpecifier = normalizeCanvasModuleSpecifier(specifier);
      const resolved = MODULE_WHITELIST[normalizedSpecifier];
      if (resolved === undefined) {
        throw new Error(
          `Import "${specifier}" is not allowed. Canvas code may only import from: ${Object.keys(MODULE_WHITELIST).join(", ")}`,
        );
      }
      return resolved;
    };

    // The Function constructor creates a new scope. We inject only the
    // minimum globals: require, module, exports, React.
    const factory = new Function(
      "require",
      "module",
      "exports",
      "React",
      jsCode,
    );

    factory(constrainedRequire, fakeModule, moduleExports, React);

    // Step 3: Extract default export
    const Component =
      (fakeModule.exports as Record<string, unknown>).default ??
      (moduleExports as Record<string, unknown>).default;

    if (typeof Component !== "function") {
      return {
        ok: false,
        error:
          "Canvas source must `export default` a React function component. " +
          `Got ${typeof Component}.`,
      };
    }

    return { ok: true, Component: Component as React.ComponentType };
  } catch (err) {
    return {
      ok: false,
      error: `Canvas runtime error: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}
