export {
  isGitHubUrl,
  parseGitHubUrl,
  isGitRepository,
  getCurrentBranch,
  listBranches,
  listRemoteBranches,
  fetchRemote,
  getBranchInfo,
  getBranchStatus,
  checkoutBranch,
  pullBranch,
  getRemoteUrl,
  getRepoStatus,
  getCloneBaseDir,
  repoToDirName,
  dirNameToRepo,
  listClonedRepos,
  validateRepoInput,
  validateBranchName,
  sanitizeBranchName,
  type ParsedGitHubUrl,
  type RepoBranchInfo,
  type RepoStatus,
  type BranchStatus,
  type BranchValidationResult,
  type ClonedRepoInfo,
  type ValidationResult,
} from "./git-utils";

export {
  isGitAuthError,
  isSSHAuthError,
  isHTTPSAuthError,
  getGitAuthErrorType,
  getGitAuthErrorMessage,
  getGitCredentialSetupInstructions,
  getGitErrorMessage,
  withGitAuthHandling,
  type GitAuthErrorType,
  type GitCredentialInstructions,
  type GitOperationResult,
} from "./git-error-handler";
